version: '3.3'

services:
    webserver:
        image: ${WEBSERVER_IMAGE}
        volumes:
            - ${STORAGE_PATH}:/var/www/storage
            - ${WEBSERVER_CONFIG_PATH}:/etc/nginx/conf.d
        networks:
            - app
            - traefik-public
        deploy:
            placement:
                constraints:
                    - node.labels.laravel.webserver-data == true
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.services.laravel-webserver.loadbalancer.server.port=80

                # route 1: http://<domain>
                - traefik.http.routers.laravel-webserver-http.rule=Host(`${DOMAIN}`)
                - traefik.http.routers.laravel-webserver-http.entrypoints=http
                - traefik.http.routers.laravel-webserver-http.middlewares=https-redirect

                # route 2: http://www.<domain>
                - traefik.http.routers.laravel-webserver-www-http.rule=Host(`www.${DOMAIN}`)
                - traefik.http.routers.laravel-webserver-www-http.entrypoints=http
                - traefik.http.routers.laravel-webserver-www-http.middlewares=https-redirect

                # route 3: https://<domain>
                - traefik.http.routers.laravel-webserver-https.rule=Host(`${DOMAIN}`)
                - traefik.http.routers.laravel-webserver-https.entrypoints=https
                - traefik.http.routers.laravel-webserver-https.tls=true
                - traefik.http.routers.laravel-webserver-https.tls.certresolver=le

                # route 4: https://www.<domain>
                - traefik.http.routers.laravel-webserver-www-https.rule=Host(`www.${DOMAIN}`)
                - traefik.http.routers.laravel-webserver-www-https.entrypoints=https
                - traefik.http.routers.laravel-webserver-www-https.tls=true
                - traefik.http.routers.laravel-webserver-www-https.tls.certresolver=le

    app:
        image: ${APP_IMAGE}
        volumes:
            - ${ENV_FILE}:/var/www/.env:ro
            - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini:ro
            - ${STORAGE_PATH}:/var/www/storage
        networks:
            - app
        deploy:
            placement:
                constraints:
                    - node.labels.laravel.app-data == true

    queue_worker:
        image: ${QUEUE_WORKER_IMAGE}
        volumes:
            - ${ENV_FILE}:/var/www/.env:ro
            - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini:ro
            - ${STORAGE_PATH}:/var/www/storage
        deploy:
            placement:
                constraints:
                    - node.labels.laravel.queue-worker-data == true

    schedule_runner:
        image: ${SCHEDULE_RUNNER_IMAGE}
        volumes:
            - ${ENV_FILE}:/var/www/.env:ro
            - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini:ro
            - ${STORAGE_PATH}:/var/www/storage
        deploy:
            placement:
                constraints:
                    - node.labels.laravel.schedule-runner-data == true

networks:
    app:
        driver: overlay
    traefik-public:
        external: true
