version: '3.3'

services:

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        deploy:
            placement:
                constraints:
                    - node.labels.db.mysql-data == true
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - db

    pma:
        image: phpmyadmin
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.services.db-pma.loadbalancer.server.port=80

                # route 1: http://<domain>
                - traefik.http.routers.db-pma-http.rule=Host(`${PMA_DOMAIN}`)
                - traefik.http.routers.db-pma-http.entrypoints=http
                - traefik.http.routers.db-pma-http.middlewares=https-redirect

                # route 2: https://<domain>
                - traefik.http.routers.db-pma-https.rule=Host(`${PMA_DOMAIN}`)
                - traefik.http.routers.db-pma-https.entrypoints=https
                - traefik.http.routers.db-pma-https.tls=true
                - traefik.http.routers.db-pma-https.tls.certresolver=le

        networks:
            - db
            - traefik-public

networks:
    traefik-public:
        external: true
    db:
